### ISSUE TITLE
I could not join the voice channel: Error: FFMPEG not found!

### ISSUE THREAD

**Issue by Robin-Sch** [AlphaCode-YourBotGuide/AlphaCode-1Music#2]
how can i fix this error?

**Comment by Androz2091** [comment]
http://lmgtfy.com/?q=how%20to%20install%20ffmpeg%20windows%2010&s=g

**Comment by Androz2091** [comment]
And if you're on Linux http://lmgtfy.com/?q=how%20to%20install%20ffmpeg%20linux&s=g
